# Generated by Django 5.0 on 2023-12-19 23:15

import django.core.validators
import django.db.models.deletion
import job.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('job_type', models.CharField(
                    choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary'), ('Intership', 'Intership')],
                    default='Permanent', max_length=20)),
                ('education', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Phd', 'Phd')],
                                               default='Bachelor', max_length=20)),
                ('industry', models.CharField(
                    choices=[('Business', 'Business'), ('Information Technology', 'It'), ('Banking', 'Banking'),
                             ('Education', 'Education'), ('Telecomunication', 'Telecomunication'),
                             ('Others', 'Others')], default='Business', max_length=30)),
                ('experience', models.CharField(
                    choices=[('No experience', 'No Experience'), ('1 Year', 'One Year'), ('2 years', 'Two Year'),
                             ('3 years above', 'Three Year Plus')], default='No experience', max_length=20)),
                ('salary', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1),
                                                                      django.core.validators.MaxValueValidator(
                                                                          1000000)])),
                ('positions', models.IntegerField(default=1)),
                ('company', models.CharField(max_length=100, null=True)),
                ('lastDate', models.DateTimeField(default=job.models.return_date_time)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
